services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: predico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - disease_network
    restart: unless-stopped

  web:
    build: .
    container_name: django_app
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 disease_prediction.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/pics
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=disease_prediction.settings
      - DB_HOST=db
      - DB_NAME=predico
      - DB_USER=postgres
      - DB_PASSWORD=postgresql
      - DB_PORT=5432
    networks:
      - disease_network
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  disease_network:
    driver: bridge

